language: rust
rust:
  - stable
  - 1.32.0 # development version
cache: cargo
# TODO: Upload to Github Releases
# see: https://docs.travis-ci.com/user/deployment/releases
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
