[package]
name = "vnote-cli"
version = "0.1.0"
authors = ["Willem Victor"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_yaml = "0.8"
clap = "2.32"
uuid = { version = "0.7", features = ["serde", "v4"] }
